Refactor Template detail table to use Inventory table
RedHatInsights/patchman-ui pull request #1028
Opened 2023-04-17 20:27 UTC by leSamo

There should be almost no change in functionality, aside from added Tags column and sortable OS column in Template detail table.

2023-04-19 16:01 UTC, mkholjuraev requested changes
Codewise looks good to me. A few comments I have faced an issue while searching for a system in the template review systems step that needs to be fixed.

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/59481011/233133698-36ff2210-7cf6-46c8-96b1-c39f359d5189.png">

2023-04-19 20:24 UTC, leSamo commented on src/Utilities/api.js
> +    const id = params.id;
I wish I didn't need to do this, but `getEntities` function is setup this way along with all other endpoints using InventoryTable, so I'll either refactor this single function or refactor 4 or so other endpoints along with `getEntities` function 😢

2023-04-19 22:48 UTC, leSamo commented on src/SmartComponents/PatchSetDetail/PatchSetDetail.js
> +    //console.log("aaaaaaaaaaaaaaaaa", a, totalItems);
Whoops :sweat_smile:

2023-04-19 22:51 UTC, leSamo commented on src/SmartComponents/PatchSetDetail/PatchSetDetail.js
> +        inventory?.current?.onRefreshData({ timestamp: Date.now() });
Good question! No it doesn't, it's filtered out.

2023-04-19 22:59 UTC, leSamo commented on src/SmartComponents/PatchSetDetail/PatchSetDetail.js
> +            //dispatch(fetchPatchSetDetailSystemsAction(patchSetId, queryParams));
Good catch, I removed that line.

2023-04-19 22:59 UTC, leSamo commented
@mkholjuraev thanks for review! I addressed all your comments.

2023-04-25 10:12 UTC, AsToNlele approved these changes
With the fix works great, good job! Only a small nitpick "Upto" should propably be "Up to"
![image](https://user-images.githubusercontent.com/20592948/234246130-9c242997-e427-4932-8f6f-28cab72ad042.png)

2023-04-25 10:39 UTC, merged