chore: upgrade react-router-dom to v6
RedHatInsights/patchman-ui pull request #1055
Opened 2023-05-17 11:53 UTC by AsToNlele

# Description

Associated Jira ticket: # [SPM-1858](https://issues.redhat.com/browse/SPM-1858)

# Checklist:

- [ ] The commit message has the Jira ticket linked
- [ ] PR has a short description
- [ ] Screenshots before and after the change are added
- [ ] Tests for the changes have been added
- [ ] README.md is updated if necessary
- [ ] Needs additional dependent work

2023-06-26 13:03 UTC, AsToNlele commented
I'll edit the description steps later

2023-06-27 11:17 UTC, AsToNlele commented
After Frontend components have been upgraded, there is one less step :tada:

2023-06-27 17:20 UTC, bastilian commented on src/Routes.js
> +            <Router>
Something is not right here. This should throw an error like "Router in Router not allowed".

2023-06-27 17:36 UTC, bastilian commented on src/Routes.js
> +            <Router>
🙈 my bad. I didn't see the `as` for the import. But maybe we can avoid that renaming. What if we use `AdvisorRoutes` for this const and not rename the `Routes` component from react router?

2023-06-27 17:45 UTC, bastilian approved these changes
Nice job! Thank you @AsToNlele!

2023-06-27 17:46 UTC, bastilian commented
@AsToNlele Just out of precaution, we should get a second approval from @RedHatInsights/team-interact before merging.

2023-06-27 18:05 UTC, bastilian requested changes
Sorry, but I did find issues doublechecking on `/preview`.
There everything appears to fall apart. :/

2023-06-28 18:50 UTC, bastilian commented on src/Routes.js
> +                    navigate(`/${event.navId}`);
I think, this should use `chrome.appNavClick` like here[0] in order to work correctly. We have encountered with navigate where it does a full page refresh, which it shouldn't.

[0] https://github.com/RedHatInsights/compliance-frontend/pull/1892/files#diff-3d74dddefb6e35fbffe3c76ec0712d5c416352d9449e2fcc8210a9dee57dff67R23

2023-06-30 13:22 UTC, AsToNlele commented
/retest

2023-07-04 11:58 UTC, AsToNlele commented
/retest

2023-07-17 21:47 UTC, johnsonm325 approved these changes
This seems to work okay.

There is a bug when you apply an os filter to the systems table and then try to refresh the page. But it exists in stage, so isn't related to this PR. I'm creating a card.

2023-07-25 10:50 UTC, bastilian commented on src/Routes.js
> +                    chrome.appNavClick(`/${event.navId}`);
According to the platform team, this whole part related to `APP_NAVIGATION` can and should be removed (see https://github.com/RedHatInsights/compliance-frontend/pull/1892/files#diff-3d74dddefb6e35fbffe3c76ec0712d5c416352d9449e2fcc8210a9dee57dff67 for example)

2023-08-02 10:12 UTC, merged

2023-08-07 14:34 UTC, mkholjuraev commented
:tada: This PR is included in version 1.63.11 :tada:

The release is available on [GitHub release](https://github.com/RedHatInsights/patchman-ui/releases/tag/v1.63.11)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: