feat(inventory groups): add inv groups column and filter
RedHatInsights/patchman-ui pull request #1092
Opened 2023-07-18 09:37 UTC by Fewwy

# Description

Associated Jira ticket: # (issue)

Please include a summary of the change, what this fixes/creates/improves.

# How to test the PR

Please include steps to test your PR.

# Before the change

# After the change

# Dependent work link

# Checklist:

- [ ] The commit message has the Jira ticket linked
- [ ] PR has a short description
- [ ] Screenshots before and after the change are added
- [ ] Tests for the changes have been added
- [ ] README.md is updated if necessary
- [ ] Needs additional dependent work

2023-07-18 11:04 UTC, leSamo requested changes
When I try to disable feature flag:
![Screenshot from 2023-07-18 12-01-58](https://github.com/RedHatInsights/patchman-ui/assets/8426204/d3d198a2-58af-433b-a2a9-ad44b8aefc68)

When I try to filter:
[Screencast from 2023-07-18 11-59-08.webm](https://github.com/RedHatInsights/patchman-ui/assets/8426204/4c3a7152-a1d0-4ab5-8388-66e91c65275c)

2023-07-19 14:15 UTC, mkholjuraev commented
/retest

2023-07-20 07:56 UTC, Fewwy commented
/retest

2023-07-25 09:53 UTC, gkarat requested changes
When I apply the group filter by choosing a group that has some hosts, I see that data is not filtered. However, the backend already has this filter implemented https://issues.redhat.com/browse/ESSNTL-4817?focusedId=22636009&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22636009. I also tried to edit and resend the request (to /api/patch/v3/system) with this parameter and it indeed filtered hosts. So let's support it here too within this PR.

The group column is mapped properly and for some hosts I see the link is rendered and it works correct ✅

2023-07-25 09:53 UTC, gkarat commented on src/Utilities/SystemsHelpers.js
> +            //change this link to a InsightsLink after router upgrade
```suggestion
            // TODO: change this link to a InsightsLink after router upgrade
```

2023-09-01 08:42 UTC, closed without merging