SPM-755 Add bulk remediation for systems and advisories
RedHatInsights/patchman-ui pull request #469
Opened 2021-03-18 10:56 UTC by jiridostal

This PR implement the Patch side of bulk remediation.
**There is a bug that prevents the remediation from creating - the wizard goes to the last step and than fails, platform is working on it**

The purpose is to demonstrate the behavior on Patch side.

2021-03-18 13:20 UTC, mkholjuraev requested changes
I am afraid the PatchRemediationButton component is missing from the PR commit.

2021-03-18 13:24 UTC, jiridostal commented
Fixed!

2021-03-18 14:46 UTC, mkholjuraev commented on src/Utilities/Helpers.js
> +        console.log(await res);
I believe this needs to be deleted :)

2021-03-18 14:47 UTC, mkholjuraev reviewed
It looks that 2 remediation modals are being mounted in the Systems page, when I close one model, the other is displayed. Otherwise working as described.

2021-03-25 10:23 UTC, merged

2021-03-25 14:47 UTC, jiridostal commented
:tada: This PR is included in version 1.14.0 :tada:

The release is available on:
- [GitHub release](https://github.com/RedHatInsights/patchman-ui/releases/tag/v1.14.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@redhat-cloud-services/frontend-components-inventory-patchman/v/1.14.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: