fix(SPM-1492): system details page refreshs after patch-set change
RedHatInsights/patchman-ui pull request #797
Opened 2022-05-12 09:45 UTC by mkholjuraev

Resolves: https://issues.redhat.com/browse/SPM-1492. I am not able to do API request other than the type GET, theoratically just adding `patchSetState.shouldRefresh` to the the hook dependency should do the trick, most probably. Thus, please run this PR locally to make sure it does the fix.

To reproduce:
1. Assign system to a patch set via action on system detail page
2. The page continues to display old patch set name a needs to be refreshed to display new patch set name

2022-05-13 09:30 UTC, MichalSajdik reviewed
I noticed that in https://github.com/RedHatInsights/patchman-ui/pull/798
you have similiar changes with different commit id's. I think it should be consistent

2022-05-13 09:31 UTC, MichalSajdik requested changes
the comment above

2022-05-13 11:44 UTC, mkholjuraev commented
@MichalSajdik thanks for having a look. Yeap, I forgot to checkout to a new branch from master branch. Issue is resolved.

2022-05-17 08:37 UTC, mkholjuraev commented
@MichalSajdik thanks!

2022-05-17 08:37 UTC, merged

2022-05-17 08:59 UTC, jiridostal commented
:tada: This PR is included in version 1.47.2 :tada:

The release is available on:
- [GitHub release](https://github.com/RedHatInsights/patchman-ui/releases/tag/v1.47.2)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@redhat-cloud-services/frontend-components-inventory-patchman/v/1.47.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: