SPM-1729: Show only relevant OS filter options across tables
RedHatInsights/patchman-ui pull request #872
Opened 2022-09-15 13:30 UTC by gkarat

Implements https://issues.redhat.com/browse/SPM-1729.

This changes the behavior of the OS filter across tables. The filter now only shows the options that are relevant and available for the user's account. The options are requested from the Inventory API.

## How to test

1. Check the following pages and components to contain the same values for the OS filter:
1.1. https://stage.foo.redhat.com:1337/beta/insights/patch/systems
1.2. https://stage.foo.redhat.com:1337/beta/insights/patch/advisories/${advisory_id}
1.3. https://stage.foo.redhat.com:1337/beta/insights/patch/templates: create patch template wizard component.
2. Check whether a call to the Inventory API's /operating_system is made in all pages.
3. Check chips/filter selection behavior and URL parameters update.

## Screenshots

![Screenshot 2022-09-15 at 15-27-15 Patch template - Patch Red Hat Insights](https://user-images.githubusercontent.com/31385370/190415978-caffe7d1-73f1-492e-94a9-82a16026195f.png)
![Screenshot 2022-09-15 at 15-26-53 FEDORA-EPEL-2022-929440e4dc - Advisories - Patch Red Hat Insights](https://user-images.githubusercontent.com/31385370/190415985-1bdea00b-26d1-42cb-96d1-ae55b247f237.png)
![Screenshot 2022-09-15 at 15-26-19 Systems - Patch Red Hat Insights](https://user-images.githubusercontent.com/31385370/190415990-1f4243de-0510-409f-82b4-d561073ff422.png)

2022-09-19 11:10 UTC, mkholjuraev requested changes
Overall code looks good. But, I would love to see a few duplicated code to be removed by making created OS filter hook more dynamic.  (I am checking how much effort is needed to use the default `operatingSystem` filter from [the Inventory table component](https://github.com/RedHatInsights/insights-inventory-frontend/blob/master/src/components/InventoryTable/EntityTableToolbar.js#L133))

2022-09-19 11:10 UTC, mkholjuraev commented on src/PresentationalComponents/Filters/OsVersionFilter.js
> +    ).map((version) => version.substr(5));
substr function is [deprecated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr). Use [substring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring) instead.

2022-09-20 15:04 UTC, gkarat commented on src/SmartComponents/PatchSetWizard/steps/ReviewSystems.js
> -import osVersionFilter from '../../../PresentationalComponents/Filters/OsVersionFilter';
@mkholjuraev, thanks, this sounds reasonable. I have revisited this piece of code in the latest commit, PTAL

2022-09-20 15:25 UTC, mkholjuraev approved these changes
Looks perfect. @gkarat thank you! Did not run it though.

2022-09-26 07:50 UTC, merged

2022-09-26 08:06 UTC, jiridostal commented
:tada: This PR is included in version 1.51.0 :tada:

The release is available on:
- [GitHub release](https://github.com/RedHatInsights/patchman-ui/releases/tag/v1.51.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@redhat-cloud-services/frontend-components-inventory-patchman/v/1.51.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: